//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.24 at 04:40:46 PM IST 
//


package com.nationstar.reportengine.disbursement.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nationstar.reportengine.disbursement.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nationstar.reportengine.disbursement.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TRIMSInterface }
     * 
     */
    public TRIMSInterface createTRIMSInterface() {
        return new TRIMSInterface();
    }

    /**
     * Create an instance of {@link TRIMSInterface.TRIMSTransaction }
     * 
     */
    public TRIMSInterface.TRIMSTransaction createTRIMSInterfaceTRIMSTransaction() {
        return new TRIMSInterface.TRIMSTransaction();
    }

    /**
     * Create an instance of {@link TRIMSInterface.TRIMSTransaction.ChequeInformation }
     * 
     */
    public TRIMSInterface.TRIMSTransaction.ChequeInformation createTRIMSInterfaceTRIMSTransactionChequeInformation() {
        return new TRIMSInterface.TRIMSTransaction.ChequeInformation();
    }

    /**
     * Create an instance of {@link TRIMSInterface.TRIMSTransaction.ChequeInformation.RmtInf }
     * 
     */
    public TRIMSInterface.TRIMSTransaction.ChequeInformation.RmtInf createTRIMSInterfaceTRIMSTransactionChequeInformationRmtInf() {
        return new TRIMSInterface.TRIMSTransaction.ChequeInformation.RmtInf();
    }

    /**
     * Create an instance of {@link TRIMSInterface.TRIMSTransaction.Amount }
     * 
     */
    public TRIMSInterface.TRIMSTransaction.Amount createTRIMSInterfaceTRIMSTransactionAmount() {
        return new TRIMSInterface.TRIMSTransaction.Amount();
    }

    /**
     * Create an instance of {@link TRIMSInterface.TRIMSTransaction.DebitAccount }
     * 
     */
    public TRIMSInterface.TRIMSTransaction.DebitAccount createTRIMSInterfaceTRIMSTransactionDebitAccount() {
        return new TRIMSInterface.TRIMSTransaction.DebitAccount();
    }

    /**
     * Create an instance of {@link TRIMSInterface.TRIMSTransaction.CreditAccount }
     * 
     */
    public TRIMSInterface.TRIMSTransaction.CreditAccount createTRIMSInterfaceTRIMSTransactionCreditAccount() {
        return new TRIMSInterface.TRIMSTransaction.CreditAccount();
    }

    /**
     * Create an instance of {@link TRIMSInterface.TRIMSTransaction.AdditionalPayeeInformation }
     * 
     */
    public TRIMSInterface.TRIMSTransaction.AdditionalPayeeInformation createTRIMSInterfaceTRIMSTransactionAdditionalPayeeInformation() {
        return new TRIMSInterface.TRIMSTransaction.AdditionalPayeeInformation();
    }

    /**
     * Create an instance of {@link TRIMSInterface.TRIMSTransaction.ChequeInformation.RmtInf.Strd }
     * 
     */
    public TRIMSInterface.TRIMSTransaction.ChequeInformation.RmtInf.Strd createTRIMSInterfaceTRIMSTransactionChequeInformationRmtInfStrd() {
        return new TRIMSInterface.TRIMSTransaction.ChequeInformation.RmtInf.Strd();
    }

}
