//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.24 at 04:40:46 PM IST 
//


package com.nationstar.reportengine.disbursement.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;

import org.eclipse.persistence.oxm.annotations.XmlCDATA;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TRIMSTransaction" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ClientTransactionReferenceNumber">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="64"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="TransactionType">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="CHECK"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="ValueDate">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *                         &lt;pattern value="((000[1-9])|(00[1-9][0-9])|(0[1-9][0-9]{2})|([1-9][0-9]{3}))-((0[1-9])|(1[012]))-((0[1-9])|([12][0-9])|(3[01]))"/>
 *                         &lt;maxInclusive value="9999-12-31"/>
 *                         &lt;minInclusive value="0001-01-01"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Amount">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;>Decimal18.2">
 *                           &lt;attribute name="Ccy" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="DebitAccount">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="AccountNumber">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="34"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="RoutingNumber">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="9"/>
 *                                   &lt;maxLength value="11"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="CreditAccount">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PayeeName">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="70"/>
 *                                   &lt;pattern value="[ -~]+"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="AdditionalPayeeInformation">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="AddressLine1">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="55"/>
 *                                   &lt;pattern value="[ -~]+"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Town">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="30"/>
 *                                   &lt;pattern value="[ -~]+"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="State">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;maxLength value="2"/>
 *                                   &lt;enumeration value="AL"/>
 *                                   &lt;enumeration value="AK"/>
 *                                   &lt;enumeration value="AS"/>
 *                                   &lt;enumeration value="AZ"/>
 *                                   &lt;enumeration value="AR"/>
 *                                   &lt;enumeration value="CA"/>
 *                                   &lt;enumeration value="CO"/>
 *                                   &lt;enumeration value="DE"/>
 *                                   &lt;enumeration value="DC"/>
 *                                   &lt;enumeration value="FL"/>
 *                                   &lt;enumeration value="GA"/>
 *                                   &lt;enumeration value="GU"/>
 *                                   &lt;enumeration value="HI"/>
 *                                   &lt;enumeration value="ID"/>
 *                                   &lt;enumeration value="IL"/>
 *                                   &lt;enumeration value="IN"/>
 *                                   &lt;enumeration value="IA"/>
 *                                   &lt;enumeration value="KS"/>
 *                                   &lt;enumeration value="KY"/>
 *                                   &lt;enumeration value="LA"/>
 *                                   &lt;enumeration value="ME"/>
 *                                   &lt;enumeration value="MD"/>
 *                                   &lt;enumeration value="MH"/>
 *                                   &lt;enumeration value="MA"/>
 *                                   &lt;enumeration value="MI"/>
 *                                   &lt;enumeration value="FM"/>
 *                                   &lt;enumeration value="MN"/>
 *                                   &lt;enumeration value="MS"/>
 *                                   &lt;enumeration value="MO"/>
 *                                   &lt;enumeration value="MT"/>
 *                                   &lt;enumeration value="NE"/>
 *                                   &lt;enumeration value="NV"/>
 *                                   &lt;enumeration value="NH"/>
 *                                   &lt;enumeration value="NJ"/>
 *                                   &lt;enumeration value="NM"/>
 *                                   &lt;enumeration value="NY"/>
 *                                   &lt;enumeration value="NC"/>
 *                                   &lt;enumeration value="ND"/>
 *                                   &lt;enumeration value="MP"/>
 *                                   &lt;enumeration value="OH"/>
 *                                   &lt;enumeration value="OK"/>
 *                                   &lt;enumeration value="OR"/>
 *                                   &lt;enumeration value="PW"/>
 *                                   &lt;enumeration value="PA"/>
 *                                   &lt;enumeration value="PR"/>
 *                                   &lt;enumeration value="RI"/>
 *                                   &lt;enumeration value="SC"/>
 *                                   &lt;enumeration value="SD"/>
 *                                   &lt;enumeration value="TN"/>
 *                                   &lt;enumeration value="TX"/>
 *                                   &lt;enumeration value="UT"/>
 *                                   &lt;enumeration value="VT"/>
 *                                   &lt;enumeration value="VA"/>
 *                                   &lt;enumeration value="VI"/>
 *                                   &lt;enumeration value="WA"/>
 *                                   &lt;enumeration value="WV"/>
 *                                   &lt;enumeration value="WI"/>
 *                                   &lt;enumeration value="WY"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Zip">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="9"/>
 *                                   &lt;pattern value="[ -~]+"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="ChequeInformation">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ChequeNumber">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="50"/>
 *                                   &lt;pattern value="[ -~]+"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="DlvryMtd">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="10"/>
 *                                   &lt;pattern value="[ -~]+"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="FrmsCd">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="18"/>
 *                                   &lt;pattern value="[ -~]+"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="RmtInf" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Strd" maxOccurs="unbounded">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="RltdDt">
 *                                                   &lt;simpleType>
 *                                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
 *                                                       &lt;pattern value="((000[1-9])|(00[1-9][0-9])|(0[1-9][0-9]{2})|([1-9][0-9]{3}))-((0[1-9])|(1[012]))-((0[1-9])|([12][0-9])|(3[01]))"/>
 *                                                       &lt;maxInclusive value="9999-12-31"/>
 *                                                       &lt;minInclusive value="0001-01-01"/>
 *                                                     &lt;/restriction>
 *                                                   &lt;/simpleType>
 *                                                 &lt;/element>
 *                                                 &lt;element name="Nb">
 *                                                   &lt;simpleType>
 *                                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                       &lt;minLength value="1"/>
 *                                                       &lt;maxLength value="35"/>
 *                                                       &lt;pattern value="[ -~]+"/>
 *                                                     &lt;/restriction>
 *                                                   &lt;/simpleType>
 *                                                 &lt;/element>
 *                                                 &lt;element name="AddtlRmtInf">
 *                                                   &lt;simpleType>
 *                                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                                       &lt;minLength value="1"/>
 *                                                       &lt;maxLength value="30"/>
 *                                                       &lt;pattern value="[ -~]+"/>
 *                                                     &lt;/restriction>
 *                                                   &lt;/simpleType>
 *                                                 &lt;/element>
 *                                                 &lt;element name="RmtdAmt">
 *                                                   &lt;simpleType>
 *                                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                                                       &lt;totalDigits value="16"/>
 *                                                       &lt;fractionDigits value="2"/>
 *                                                       &lt;pattern value="[0-9]{1,14}[.][0-9]{2}"/>
 *                                                     &lt;/restriction>
 *                                                   &lt;/simpleType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="ClientID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trimsTransaction"
})
@XmlRootElement(name = "TRIMSInterface")
public class TRIMSInterface {

    @XmlElement(name = "TRIMSTransaction", required = true)
    protected List<TRIMSInterface.TRIMSTransaction> trimsTransaction;
    @XmlAttribute(name = "ClientID", required = true)
    protected String clientID;

    /**
     * Gets the value of the trimsTransaction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trimsTransaction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTRIMSTransaction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TRIMSInterface.TRIMSTransaction }
     * 
     * 
     */
    public List<TRIMSInterface.TRIMSTransaction> getTRIMSTransaction() {
        if (trimsTransaction == null) {
            trimsTransaction = new ArrayList<TRIMSInterface.TRIMSTransaction>();
        }
        return this.trimsTransaction;
    }

    /**
     * Gets the value of the clientID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientID() {
        return clientID;
    }

    /**
     * Sets the value of the clientID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientID(String value) {
        this.clientID = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ClientTransactionReferenceNumber">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="64"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="TransactionType">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="CHECK"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="ValueDate">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
     *               &lt;pattern value="((000[1-9])|(00[1-9][0-9])|(0[1-9][0-9]{2})|([1-9][0-9]{3}))-((0[1-9])|(1[012]))-((0[1-9])|([12][0-9])|(3[01]))"/>
     *               &lt;maxInclusive value="9999-12-31"/>
     *               &lt;minInclusive value="0001-01-01"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Amount">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;>Decimal18.2">
     *                 &lt;attribute name="Ccy" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="DebitAccount">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="AccountNumber">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="34"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="RoutingNumber">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="9"/>
     *                         &lt;maxLength value="11"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="CreditAccount">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PayeeName">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="70"/>
     *                         &lt;pattern value="[ -~]+"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="AdditionalPayeeInformation">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="AddressLine1">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="55"/>
     *                         &lt;pattern value="[ -~]+"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Town">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="30"/>
     *                         &lt;pattern value="[ -~]+"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="State">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;maxLength value="2"/>
     *                         &lt;enumeration value="AL"/>
     *                         &lt;enumeration value="AK"/>
     *                         &lt;enumeration value="AS"/>
     *                         &lt;enumeration value="AZ"/>
     *                         &lt;enumeration value="AR"/>
     *                         &lt;enumeration value="CA"/>
     *                         &lt;enumeration value="CO"/>
     *                         &lt;enumeration value="DE"/>
     *                         &lt;enumeration value="DC"/>
     *                         &lt;enumeration value="FL"/>
     *                         &lt;enumeration value="GA"/>
     *                         &lt;enumeration value="GU"/>
     *                         &lt;enumeration value="HI"/>
     *                         &lt;enumeration value="ID"/>
     *                         &lt;enumeration value="IL"/>
     *                         &lt;enumeration value="IN"/>
     *                         &lt;enumeration value="IA"/>
     *                         &lt;enumeration value="KS"/>
     *                         &lt;enumeration value="KY"/>
     *                         &lt;enumeration value="LA"/>
     *                         &lt;enumeration value="ME"/>
     *                         &lt;enumeration value="MD"/>
     *                         &lt;enumeration value="MH"/>
     *                         &lt;enumeration value="MA"/>
     *                         &lt;enumeration value="MI"/>
     *                         &lt;enumeration value="FM"/>
     *                         &lt;enumeration value="MN"/>
     *                         &lt;enumeration value="MS"/>
     *                         &lt;enumeration value="MO"/>
     *                         &lt;enumeration value="MT"/>
     *                         &lt;enumeration value="NE"/>
     *                         &lt;enumeration value="NV"/>
     *                         &lt;enumeration value="NH"/>
     *                         &lt;enumeration value="NJ"/>
     *                         &lt;enumeration value="NM"/>
     *                         &lt;enumeration value="NY"/>
     *                         &lt;enumeration value="NC"/>
     *                         &lt;enumeration value="ND"/>
     *                         &lt;enumeration value="MP"/>
     *                         &lt;enumeration value="OH"/>
     *                         &lt;enumeration value="OK"/>
     *                         &lt;enumeration value="OR"/>
     *                         &lt;enumeration value="PW"/>
     *                         &lt;enumeration value="PA"/>
     *                         &lt;enumeration value="PR"/>
     *                         &lt;enumeration value="RI"/>
     *                         &lt;enumeration value="SC"/>
     *                         &lt;enumeration value="SD"/>
     *                         &lt;enumeration value="TN"/>
     *                         &lt;enumeration value="TX"/>
     *                         &lt;enumeration value="UT"/>
     *                         &lt;enumeration value="VT"/>
     *                         &lt;enumeration value="VA"/>
     *                         &lt;enumeration value="VI"/>
     *                         &lt;enumeration value="WA"/>
     *                         &lt;enumeration value="WV"/>
     *                         &lt;enumeration value="WI"/>
     *                         &lt;enumeration value="WY"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Zip">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="9"/>
     *                         &lt;pattern value="[ -~]+"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ChequeInformation">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ChequeNumber">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="50"/>
     *                         &lt;pattern value="[ -~]+"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="DlvryMtd">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="10"/>
     *                         &lt;pattern value="[ -~]+"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="FrmsCd">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="18"/>
     *                         &lt;pattern value="[ -~]+"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="RmtInf" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Strd" maxOccurs="unbounded">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="RltdDt">
     *                                         &lt;simpleType>
     *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
     *                                             &lt;pattern value="((000[1-9])|(00[1-9][0-9])|(0[1-9][0-9]{2})|([1-9][0-9]{3}))-((0[1-9])|(1[012]))-((0[1-9])|([12][0-9])|(3[01]))"/>
     *                                             &lt;maxInclusive value="9999-12-31"/>
     *                                             &lt;minInclusive value="0001-01-01"/>
     *                                           &lt;/restriction>
     *                                         &lt;/simpleType>
     *                                       &lt;/element>
     *                                       &lt;element name="Nb">
     *                                         &lt;simpleType>
     *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                             &lt;minLength value="1"/>
     *                                             &lt;maxLength value="35"/>
     *                                             &lt;pattern value="[ -~]+"/>
     *                                           &lt;/restriction>
     *                                         &lt;/simpleType>
     *                                       &lt;/element>
     *                                       &lt;element name="AddtlRmtInf">
     *                                         &lt;simpleType>
     *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                                             &lt;minLength value="1"/>
     *                                             &lt;maxLength value="30"/>
     *                                             &lt;pattern value="[ -~]+"/>
     *                                           &lt;/restriction>
     *                                         &lt;/simpleType>
     *                                       &lt;/element>
     *                                       &lt;element name="RmtdAmt">
     *                                         &lt;simpleType>
     *                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *                                             &lt;totalDigits value="16"/>
     *                                             &lt;fractionDigits value="2"/>
     *                                             &lt;pattern value="[0-9]{1,14}[.][0-9]{2}"/>
     *                                           &lt;/restriction>
     *                                         &lt;/simpleType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "clientTransactionReferenceNumber",
        "transactionType",
        "valueDate",
        "amount",
        "debitAccount",
        "creditAccount",
        "additionalPayeeInformation",
        "chequeInformation"
    })
    public static class TRIMSTransaction {

        @XmlElement(name = "ClientTransactionReferenceNumber", required = true)
        protected String clientTransactionReferenceNumber;
        @XmlElement(name = "TransactionType", required = true)
        protected String transactionType;
        @XmlElement(name = "ValueDate", required = true)
        protected XMLGregorianCalendar valueDate;
        @XmlElement(name = "Amount", required = true)
        protected TRIMSInterface.TRIMSTransaction.Amount amount;
        @XmlElement(name = "DebitAccount", required = true)
        protected TRIMSInterface.TRIMSTransaction.DebitAccount debitAccount;
        @XmlElement(name = "CreditAccount", required = true)
        protected TRIMSInterface.TRIMSTransaction.CreditAccount creditAccount;
        @XmlElement(name = "AdditionalPayeeInformation", required = true)
        protected TRIMSInterface.TRIMSTransaction.AdditionalPayeeInformation additionalPayeeInformation;
        @XmlElement(name = "ChequeInformation", required = true)
        protected TRIMSInterface.TRIMSTransaction.ChequeInformation chequeInformation;

        /**
         * Gets the value of the clientTransactionReferenceNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClientTransactionReferenceNumber() {
            return clientTransactionReferenceNumber;
        }

        /**
         * Sets the value of the clientTransactionReferenceNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClientTransactionReferenceNumber(String value) {
            this.clientTransactionReferenceNumber = value;
        }

        /**
         * Gets the value of the transactionType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransactionType() {
            return transactionType;
        }

        /**
         * Sets the value of the transactionType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransactionType(String value) {
            this.transactionType = value;
        }

        /**
         * Gets the value of the valueDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getValueDate() {
            return valueDate;
        }

        /**
         * Sets the value of the valueDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setValueDate(XMLGregorianCalendar value) {
            this.valueDate = value;
        }

        /**
         * Gets the value of the amount property.
         * 
         * @return
         *     possible object is
         *     {@link TRIMSInterface.TRIMSTransaction.Amount }
         *     
         */
        public TRIMSInterface.TRIMSTransaction.Amount getAmount() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         * @param value
         *     allowed object is
         *     {@link TRIMSInterface.TRIMSTransaction.Amount }
         *     
         */
        public void setAmount(TRIMSInterface.TRIMSTransaction.Amount value) {
            this.amount = value;
        }

        /**
         * Gets the value of the debitAccount property.
         * 
         * @return
         *     possible object is
         *     {@link TRIMSInterface.TRIMSTransaction.DebitAccount }
         *     
         */
        public TRIMSInterface.TRIMSTransaction.DebitAccount getDebitAccount() {
            return debitAccount;
        }

        /**
         * Sets the value of the debitAccount property.
         * 
         * @param value
         *     allowed object is
         *     {@link TRIMSInterface.TRIMSTransaction.DebitAccount }
         *     
         */
        public void setDebitAccount(TRIMSInterface.TRIMSTransaction.DebitAccount value) {
            this.debitAccount = value;
        }

        /**
         * Gets the value of the creditAccount property.
         * 
         * @return
         *     possible object is
         *     {@link TRIMSInterface.TRIMSTransaction.CreditAccount }
         *     
         */
        public TRIMSInterface.TRIMSTransaction.CreditAccount getCreditAccount() {
            return creditAccount;
        }

        /**
         * Sets the value of the creditAccount property.
         * 
         * @param value
         *     allowed object is
         *     {@link TRIMSInterface.TRIMSTransaction.CreditAccount }
         *     
         */
        public void setCreditAccount(TRIMSInterface.TRIMSTransaction.CreditAccount value) {
            this.creditAccount = value;
        }

        /**
         * Gets the value of the additionalPayeeInformation property.
         * 
         * @return
         *     possible object is
         *     {@link TRIMSInterface.TRIMSTransaction.AdditionalPayeeInformation }
         *     
         */
        public TRIMSInterface.TRIMSTransaction.AdditionalPayeeInformation getAdditionalPayeeInformation() {
            return additionalPayeeInformation;
        }

        /**
         * Sets the value of the additionalPayeeInformation property.
         * 
         * @param value
         *     allowed object is
         *     {@link TRIMSInterface.TRIMSTransaction.AdditionalPayeeInformation }
         *     
         */
        public void setAdditionalPayeeInformation(TRIMSInterface.TRIMSTransaction.AdditionalPayeeInformation value) {
            this.additionalPayeeInformation = value;
        }

        /**
         * Gets the value of the chequeInformation property.
         * 
         * @return
         *     possible object is
         *     {@link TRIMSInterface.TRIMSTransaction.ChequeInformation }
         *     
         */
        public TRIMSInterface.TRIMSTransaction.ChequeInformation getChequeInformation() {
            return chequeInformation;
        }

        /**
         * Sets the value of the chequeInformation property.
         * 
         * @param value
         *     allowed object is
         *     {@link TRIMSInterface.TRIMSTransaction.ChequeInformation }
         *     
         */
        public void setChequeInformation(TRIMSInterface.TRIMSTransaction.ChequeInformation value) {
            this.chequeInformation = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="AddressLine1">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="55"/>
         *               &lt;pattern value="[ -~]+"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Town">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="30"/>
         *               &lt;pattern value="[ -~]+"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="State">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;maxLength value="2"/>
         *               &lt;enumeration value="AL"/>
         *               &lt;enumeration value="AK"/>
         *               &lt;enumeration value="AS"/>
         *               &lt;enumeration value="AZ"/>
         *               &lt;enumeration value="AR"/>
         *               &lt;enumeration value="CA"/>
         *               &lt;enumeration value="CO"/>
         *               &lt;enumeration value="DE"/>
         *               &lt;enumeration value="DC"/>
         *               &lt;enumeration value="FL"/>
         *               &lt;enumeration value="GA"/>
         *               &lt;enumeration value="GU"/>
         *               &lt;enumeration value="HI"/>
         *               &lt;enumeration value="ID"/>
         *               &lt;enumeration value="IL"/>
         *               &lt;enumeration value="IN"/>
         *               &lt;enumeration value="IA"/>
         *               &lt;enumeration value="KS"/>
         *               &lt;enumeration value="KY"/>
         *               &lt;enumeration value="LA"/>
         *               &lt;enumeration value="ME"/>
         *               &lt;enumeration value="MD"/>
         *               &lt;enumeration value="MH"/>
         *               &lt;enumeration value="MA"/>
         *               &lt;enumeration value="MI"/>
         *               &lt;enumeration value="FM"/>
         *               &lt;enumeration value="MN"/>
         *               &lt;enumeration value="MS"/>
         *               &lt;enumeration value="MO"/>
         *               &lt;enumeration value="MT"/>
         *               &lt;enumeration value="NE"/>
         *               &lt;enumeration value="NV"/>
         *               &lt;enumeration value="NH"/>
         *               &lt;enumeration value="NJ"/>
         *               &lt;enumeration value="NM"/>
         *               &lt;enumeration value="NY"/>
         *               &lt;enumeration value="NC"/>
         *               &lt;enumeration value="ND"/>
         *               &lt;enumeration value="MP"/>
         *               &lt;enumeration value="OH"/>
         *               &lt;enumeration value="OK"/>
         *               &lt;enumeration value="OR"/>
         *               &lt;enumeration value="PW"/>
         *               &lt;enumeration value="PA"/>
         *               &lt;enumeration value="PR"/>
         *               &lt;enumeration value="RI"/>
         *               &lt;enumeration value="SC"/>
         *               &lt;enumeration value="SD"/>
         *               &lt;enumeration value="TN"/>
         *               &lt;enumeration value="TX"/>
         *               &lt;enumeration value="UT"/>
         *               &lt;enumeration value="VT"/>
         *               &lt;enumeration value="VA"/>
         *               &lt;enumeration value="VI"/>
         *               &lt;enumeration value="WA"/>
         *               &lt;enumeration value="WV"/>
         *               &lt;enumeration value="WI"/>
         *               &lt;enumeration value="WY"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Zip">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="9"/>
         *               &lt;pattern value="[ -~]+"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "addressLine1",
            "town",
            "state",
            "zip"
        })
        public static class AdditionalPayeeInformation {

            @XmlElement(name = "AddressLine1", required = true)
            @XmlCDATA
            protected String addressLine1;
            @XmlElement(name = "Town", required = true)
            protected String town;
            @XmlElement(name = "State", required = true)
            protected String state;
            @XmlElement(name = "Zip", required = true)
            protected String zip;

            /**
             * Gets the value of the addressLine1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAddressLine1() {
                return addressLine1;
            }

            /**
             * Sets the value of the addressLine1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAddressLine1(String value) {
                this.addressLine1 = value;
            }

            /**
             * Gets the value of the town property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTown() {
                return town;
            }

            /**
             * Sets the value of the town property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTown(String value) {
                this.town = value;
            }

            /**
             * Gets the value of the state property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getState() {
                return state;
            }

            /**
             * Sets the value of the state property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setState(String value) {
                this.state = value;
            }

            /**
             * Gets the value of the zip property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getZip() {
                return zip;
            }

            /**
             * Sets the value of the zip property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setZip(String value) {
                this.zip = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;>Decimal18.2">
         *       &lt;attribute name="Ccy" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Amount {

            @XmlValue
            protected BigDecimal value;
            @XmlAttribute(name = "Ccy", required = true)
            protected String ccy;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link BigDecimal }
             *     
             */
            public BigDecimal getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigDecimal }
             *     
             */
            public void setValue(BigDecimal value) {
                this.value = value;
            }

            /**
             * Gets the value of the ccy property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCcy() {
                return ccy;
            }

            /**
             * Sets the value of the ccy property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCcy(String value) {
                this.ccy = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ChequeNumber">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="50"/>
         *               &lt;pattern value="[ -~]+"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="DlvryMtd">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="10"/>
         *               &lt;pattern value="[ -~]+"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="FrmsCd">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="18"/>
         *               &lt;pattern value="[ -~]+"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="RmtInf" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Strd" maxOccurs="unbounded">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="RltdDt">
         *                               &lt;simpleType>
         *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
         *                                   &lt;pattern value="((000[1-9])|(00[1-9][0-9])|(0[1-9][0-9]{2})|([1-9][0-9]{3}))-((0[1-9])|(1[012]))-((0[1-9])|([12][0-9])|(3[01]))"/>
         *                                   &lt;maxInclusive value="9999-12-31"/>
         *                                   &lt;minInclusive value="0001-01-01"/>
         *                                 &lt;/restriction>
         *                               &lt;/simpleType>
         *                             &lt;/element>
         *                             &lt;element name="Nb">
         *                               &lt;simpleType>
         *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                                   &lt;minLength value="1"/>
         *                                   &lt;maxLength value="35"/>
         *                                   &lt;pattern value="[ -~]+"/>
         *                                 &lt;/restriction>
         *                               &lt;/simpleType>
         *                             &lt;/element>
         *                             &lt;element name="AddtlRmtInf">
         *                               &lt;simpleType>
         *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *                                   &lt;minLength value="1"/>
         *                                   &lt;maxLength value="30"/>
         *                                   &lt;pattern value="[ -~]+"/>
         *                                 &lt;/restriction>
         *                               &lt;/simpleType>
         *                             &lt;/element>
         *                             &lt;element name="RmtdAmt">
         *                               &lt;simpleType>
         *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
         *                                   &lt;totalDigits value="16"/>
         *                                   &lt;fractionDigits value="2"/>
         *                                   &lt;pattern value="[0-9]{1,14}[.][0-9]{2}"/>
         *                                 &lt;/restriction>
         *                               &lt;/simpleType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "chequeNumber",
            "dlvryMtd",
            "frmsCd",
            "rmtInf"
        })
        public static class ChequeInformation {

            @XmlElement(name = "ChequeNumber", required = true)
            protected String chequeNumber;
            @XmlElement(name = "DlvryMtd", required = true)
            protected String dlvryMtd;
            @XmlElement(name = "FrmsCd", required = true)
            protected String frmsCd;
            @XmlElement(name = "RmtInf")
            protected TRIMSInterface.TRIMSTransaction.ChequeInformation.RmtInf rmtInf;

            /**
             * Gets the value of the chequeNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChequeNumber() {
                return chequeNumber;
            }

            /**
             * Sets the value of the chequeNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChequeNumber(String value) {
                this.chequeNumber = value;
            }

            /**
             * Gets the value of the dlvryMtd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDlvryMtd() {
                return dlvryMtd;
            }

            /**
             * Sets the value of the dlvryMtd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDlvryMtd(String value) {
                this.dlvryMtd = value;
            }

            /**
             * Gets the value of the frmsCd property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFrmsCd() {
                return frmsCd;
            }

            /**
             * Sets the value of the frmsCd property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFrmsCd(String value) {
                this.frmsCd = value;
            }

            /**
             * Gets the value of the rmtInf property.
             * 
             * @return
             *     possible object is
             *     {@link TRIMSInterface.TRIMSTransaction.ChequeInformation.RmtInf }
             *     
             */
            public TRIMSInterface.TRIMSTransaction.ChequeInformation.RmtInf getRmtInf() {
                return rmtInf;
            }

            /**
             * Sets the value of the rmtInf property.
             * 
             * @param value
             *     allowed object is
             *     {@link TRIMSInterface.TRIMSTransaction.ChequeInformation.RmtInf }
             *     
             */
            public void setRmtInf(TRIMSInterface.TRIMSTransaction.ChequeInformation.RmtInf value) {
                this.rmtInf = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Strd" maxOccurs="unbounded">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="RltdDt">
             *                     &lt;simpleType>
             *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
             *                         &lt;pattern value="((000[1-9])|(00[1-9][0-9])|(0[1-9][0-9]{2})|([1-9][0-9]{3}))-((0[1-9])|(1[012]))-((0[1-9])|([12][0-9])|(3[01]))"/>
             *                         &lt;maxInclusive value="9999-12-31"/>
             *                         &lt;minInclusive value="0001-01-01"/>
             *                       &lt;/restriction>
             *                     &lt;/simpleType>
             *                   &lt;/element>
             *                   &lt;element name="Nb">
             *                     &lt;simpleType>
             *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *                         &lt;minLength value="1"/>
             *                         &lt;maxLength value="35"/>
             *                         &lt;pattern value="[ -~]+"/>
             *                       &lt;/restriction>
             *                     &lt;/simpleType>
             *                   &lt;/element>
             *                   &lt;element name="AddtlRmtInf">
             *                     &lt;simpleType>
             *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
             *                         &lt;minLength value="1"/>
             *                         &lt;maxLength value="30"/>
             *                         &lt;pattern value="[ -~]+"/>
             *                       &lt;/restriction>
             *                     &lt;/simpleType>
             *                   &lt;/element>
             *                   &lt;element name="RmtdAmt">
             *                     &lt;simpleType>
             *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
             *                         &lt;totalDigits value="16"/>
             *                         &lt;fractionDigits value="2"/>
             *                         &lt;pattern value="[0-9]{1,14}[.][0-9]{2}"/>
             *                       &lt;/restriction>
             *                     &lt;/simpleType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "strd"
            })
            public static class RmtInf {

                @XmlElement(name = "Strd", required = true)
                protected List<TRIMSInterface.TRIMSTransaction.ChequeInformation.RmtInf.Strd> strd;

                /**
                 * Gets the value of the strd property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the strd property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getStrd().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link TRIMSInterface.TRIMSTransaction.ChequeInformation.RmtInf.Strd }
                 * 
                 * 
                 */
                public List<TRIMSInterface.TRIMSTransaction.ChequeInformation.RmtInf.Strd> getStrd() {
                    if (strd == null) {
                        strd = new ArrayList<TRIMSInterface.TRIMSTransaction.ChequeInformation.RmtInf.Strd>();
                    }
                    return this.strd;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="RltdDt">
                 *           &lt;simpleType>
                 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}date">
                 *               &lt;pattern value="((000[1-9])|(00[1-9][0-9])|(0[1-9][0-9]{2})|([1-9][0-9]{3}))-((0[1-9])|(1[012]))-((0[1-9])|([12][0-9])|(3[01]))"/>
                 *               &lt;maxInclusive value="9999-12-31"/>
                 *               &lt;minInclusive value="0001-01-01"/>
                 *             &lt;/restriction>
                 *           &lt;/simpleType>
                 *         &lt;/element>
                 *         &lt;element name="Nb">
                 *           &lt;simpleType>
                 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                 *               &lt;minLength value="1"/>
                 *               &lt;maxLength value="35"/>
                 *               &lt;pattern value="[ -~]+"/>
                 *             &lt;/restriction>
                 *           &lt;/simpleType>
                 *         &lt;/element>
                 *         &lt;element name="AddtlRmtInf">
                 *           &lt;simpleType>
                 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
                 *               &lt;minLength value="1"/>
                 *               &lt;maxLength value="30"/>
                 *               &lt;pattern value="[ -~]+"/>
                 *             &lt;/restriction>
                 *           &lt;/simpleType>
                 *         &lt;/element>
                 *         &lt;element name="RmtdAmt">
                 *           &lt;simpleType>
                 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
                 *               &lt;totalDigits value="16"/>
                 *               &lt;fractionDigits value="2"/>
                 *               &lt;pattern value="[0-9]{1,14}[.][0-9]{2}"/>
                 *             &lt;/restriction>
                 *           &lt;/simpleType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "rltdDt",
                    "nb",
                    "addtlRmtInf",
                    "rmtdAmt"
                })
                public static class Strd {

                    @XmlElement(name = "RltdDt", required = true)
                    protected XMLGregorianCalendar rltdDt;
                    @XmlElement(name = "Nb", required = true)
                    protected String nb;
                    @XmlElement(name = "AddtlRmtInf", required = true)
                    protected String addtlRmtInf;
                    @XmlElement(name = "RmtdAmt", required = true)
                    protected BigDecimal rmtdAmt;

                    /**
                     * Gets the value of the rltdDt property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link XMLGregorianCalendar }
                     *     
                     */
                    public XMLGregorianCalendar getRltdDt() {
                        return rltdDt;
                    }

                    /**
                     * Sets the value of the rltdDt property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link XMLGregorianCalendar }
                     *     
                     */
                    public void setRltdDt(XMLGregorianCalendar value) {
                        this.rltdDt = value;
                    }

                    /**
                     * Gets the value of the nb property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getNb() {
                        return nb;
                    }

                    /**
                     * Sets the value of the nb property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setNb(String value) {
                        this.nb = value;
                    }

                    /**
                     * Gets the value of the addtlRmtInf property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getAddtlRmtInf() {
                        return addtlRmtInf;
                    }

                    /**
                     * Sets the value of the addtlRmtInf property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setAddtlRmtInf(String value) {
                        this.addtlRmtInf = value;
                    }

                    /**
                     * Gets the value of the rmtdAmt property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public BigDecimal getRmtdAmt() {
                        return rmtdAmt;
                    }

                    /**
                     * Sets the value of the rmtdAmt property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link BigDecimal }
                     *     
                     */
                    public void setRmtdAmt(BigDecimal value) {
                        this.rmtdAmt = value;
                    }

                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="PayeeName">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="70"/>
         *               &lt;pattern value="[ -~]+"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "payeeName"
        })
        public static class CreditAccount {

            @XmlElement(name = "PayeeName", required = true)
            @XmlCDATA
            protected String payeeName;

            /**
             * Gets the value of the payeeName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPayeeName() {
                return payeeName;
            }

            /**
             * Sets the value of the payeeName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPayeeName(String value) {
                this.payeeName = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="AccountNumber">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="34"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="RoutingNumber">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="9"/>
         *               &lt;maxLength value="11"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "accountNumber",
            "routingNumber"
        })
        public static class DebitAccount {

            @XmlElement(name = "AccountNumber", required = true)
            protected String accountNumber;
            @XmlElement(name = "RoutingNumber", required = true)
            protected String routingNumber;

            /**
             * Gets the value of the accountNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAccountNumber() {
                return accountNumber;
            }

            /**
             * Sets the value of the accountNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAccountNumber(String value) {
                this.accountNumber = value;
            }

            /**
             * Gets the value of the routingNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRoutingNumber() {
                return routingNumber;
            }

            /**
             * Sets the value of the routingNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRoutingNumber(String value) {
                this.routingNumber = value;
            }

        }

    }

}
